# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis
language: r
sudo: required
warnings_are_errors: false
bioc_required: true

apt_packages:
  - r-cran-rjava

before_install:
  - ant init-ivy
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

env:
  global:
    - CRAN: http://cran.rstudio.com

r_packages:
  - covr
  - iplots

bioc_packages:
  - graph
  - Rgraphviz

after_success:
  - Rscript -e 'covr::codecov()'
